//引入工具类
var _mm=require("util/mm.js")

var _cart={
	//获取购物车数量
	getCartCount:function(resolve, reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/get_cart_product_count.do'),
			success:resolve,
			error:reject	
		})	
	},
	//添加商品到购物侧
	addToCar:function(productInfo,resolve, reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/add.do'),
			data:productInfo,
			success:resolve,
			error:reject	
		})	
	},
	//获取购物车内的列表数据
	getCartList:function(resolve, reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/list.do'),
			success:resolve,
			error:reject	
		})	
	},
	//购物车选中某个商品
	selectProduct:function(productId,resolve,reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/select.do'),
			data:{
				productId:productId
			},
			success:resolve,
			error:reject	
		})		
	},
	//购物车取消选中某个商品
	unselectProduct:function(productId,resolve,reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/un_select.do'),
			data:{
				productId:productId
			},
			success:resolve,
			error:reject	
		})		
	},
	//购物车全选
	selectAll:function(resolve,reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/select_all.do'),
			success:resolve,
			error:reject	
		})		
	},
	//购物车取消全选
	unselectAll:function(resolve,reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/un_select_all.do'),
			success:resolve,
			error:reject	
		})		
	},
	//更新购物车某个产品数量
	updateProduct:function(productInfo,resolve,reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/update.do'),
			data:productInfo,
			success:resolve,
			error:reject	
		})		
	},
	//移除购物车某个产品
	delateProduct:function(productIds,resolve,reject){
		_mm.requese({
			url:_mm.getServerUrl('/cart/delete_product.do'),
			data:{
				productIds:productIds
			},
			success:resolve,
			error:reject	
		})		
	}
	
}

module.exports=_cart;